"""Puertos (interfaces) del módulo comercios. Implementaciones en infrastructure."""

from __future__ import annotations

from typing import Protocol

from tarjeta.shared.domain.events import DomainEvent
from tarjeta.shared.domain.types import EntityId

from .comercio import Comercio, EstadoComercio
from .invitacion import Invitacion
from .sucursal import Sucursal, SucursalCercana
from .turno import Turno
from .usuario import UsuarioComercio


class ComercioRepository(Protocol):
    async def agregar(self, comercio: Comercio) -> None: ...
    async def guardar(self, comercio: Comercio) -> None: ...
    async def obtener(self, id: EntityId) -> Comercio | None: ...
    async def obtener_por_cuit(self, cuit: str) -> Comercio | None: ...
    async def listar(self, estados: list[EstadoComercio] | None = None) -> list[Comercio]: ...


class SucursalRepository(Protocol):
    async def agregar(self, sucursal: Sucursal) -> None: ...
    async def guardar(self, sucursal: Sucursal) -> None: ...
    async def obtener(self, id: EntityId) -> Sucursal | None: ...
    async def listar_por_comercio(self, id_comercio: EntityId) -> list[Sucursal]: ...
    async def cercanas(
        self, *, lat: float, lon: float, radio_m: float, limite: int
    ) -> list[SucursalCercana]: ...


class UsuarioComercioRepository(Protocol):
    async def agregar(self, usuario: UsuarioComercio) -> None: ...
    async def guardar(self, usuario: UsuarioComercio) -> None: ...
    async def obtener(self, id: EntityId) -> UsuarioComercio | None: ...
    async def obtener_por_persona_y_comercio(
        self, id_persona: EntityId, id_comercio: EntityId
    ) -> UsuarioComercio | None: ...
    async def listar_por_comercio(self, id_comercio: EntityId) -> list[UsuarioComercio]: ...


class InvitacionRepository(Protocol):
    async def agregar(self, invitacion: Invitacion) -> None: ...
    async def guardar(self, invitacion: Invitacion) -> None: ...
    async def obtener_por_token_hash(self, token_hash: str) -> Invitacion | None: ...


class TurnoRepository(Protocol):
    async def agregar(self, turno: Turno) -> None: ...
    async def guardar(self, turno: Turno) -> None: ...
    async def turno_abierto_de(self, id_cajero: EntityId) -> Turno | None: ...


class VerificadorComerciante(Protocol):
    """§06.2: verificación por CUIT contra el padrón (padron es el único que lo contacta)."""

    async def es_comerciante(self, cuit: str) -> bool: ...


class HashPin(Protocol):
    def hash(self, pin: str) -> str: ...
    def verificar(self, hash: str, pin: str) -> bool: ...


class FirmadorEstablecimiento(Protocol):
    """QR fijo de establecimiento (§3.4): token firmado permanente por sucursal."""

    def token(self, id_sucursal: str) -> str: ...
    def verificar(self, token: str) -> str | None: ...


class Outbox(Protocol):
    async def escribir(self, eventos: list[DomainEvent]) -> None: ...
