"""padron ciudadania y registro minimo

Revision ID: c47f26a79e51
Revises: e66967947cdb
Create Date: 2026-09-03 10:19:59.856413-03:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c47f26a79e51"
down_revision: str | None = "e66967947cdb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "estado_padron",
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("dni_cifrado", sa.Text(), nullable=False),
        sa.Column("al_dia", sa.Boolean(), nullable=False),
        sa.Column("es_comerciante", sa.Boolean(), nullable=False),
        sa.Column("fecha_ultima_consulta", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id_persona"),
    )
    op.create_table(
        "excepcion_nivel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("motivo", sa.String(length=200), nullable=False),
        sa.Column("vigencia_desde", sa.DateTime(timezone=True), nullable=False),
        sa.Column("vigencia_hasta", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_excepcion_nivel_id_persona"), "excepcion_nivel", ["id_persona"], unique=False
    )
    op.create_table(
        "historial_estado_padron",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("campo", sa.String(length=40), nullable=False),
        sa.Column("valor_anterior", sa.String(length=40), nullable=False),
        sa.Column("valor_nuevo", sa.String(length=40), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("origen_consulta", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historial_estado_padron_id_persona"),
        "historial_estado_padron",
        ["id_persona"],
        unique=False,
    )
    op.create_table(
        "historial_nivel",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("nivel_anterior", sa.String(length=20), nullable=False),
        sa.Column("nivel_nuevo", sa.String(length=20), nullable=False),
        sa.Column("motivo", sa.String(length=60), nullable=False),
        sa.Column("detalle_regla_aplicada", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historial_nivel_id_persona"), "historial_nivel", ["id_persona"], unique=False
    )
    op.create_table(
        "perfil_ciudadano",
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("nivel", sa.String(length=20), nullable=False),
        sa.Column("nivel_origen", sa.String(length=20), nullable=False),
        sa.Column("numero_tarjeta", sa.String(length=16), nullable=False),
        sa.Column("estado_tarjeta", sa.String(length=20), nullable=False),
        sa.Column("tiene_tarjeta_fisica", sa.Boolean(), nullable=False),
        sa.Column("fecha_ultimo_calculo", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id_persona"),
    )
    op.create_index(
        op.f("ix_perfil_ciudadano_numero_tarjeta"),
        "perfil_ciudadano",
        ["numero_tarjeta"],
        unique=True,
    )
    # NOTA: se eliminó el drop de 'spatial_ref_sys' (tabla interna de PostGIS).
    op.add_column("persona", sa.Column("fecha_nacimiento", sa.Date(), nullable=False))
    op.alter_column("persona", "cuil_hash", existing_type=sa.VARCHAR(length=64), nullable=True)
    op.alter_column("persona", "cuil_cifrado", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("persona", "celular", existing_type=sa.VARCHAR(length=20), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("persona", "celular", existing_type=sa.VARCHAR(length=20), nullable=False)
    op.alter_column("persona", "cuil_cifrado", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("persona", "cuil_hash", existing_type=sa.VARCHAR(length=64), nullable=False)
    op.drop_column("persona", "fecha_nacimiento")
    op.drop_index(op.f("ix_perfil_ciudadano_numero_tarjeta"), table_name="perfil_ciudadano")
    op.drop_table("perfil_ciudadano")
    op.drop_index(op.f("ix_historial_nivel_id_persona"), table_name="historial_nivel")
    op.drop_table("historial_nivel")
    op.drop_index(
        op.f("ix_historial_estado_padron_id_persona"), table_name="historial_estado_padron"
    )
    op.drop_table("historial_estado_padron")
    op.drop_index(op.f("ix_excepcion_nivel_id_persona"), table_name="excepcion_nivel")
    op.drop_table("excepcion_nivel")
    op.drop_table("estado_padron")
    # ### end Alembic commands ###
