"""identidad

Revision ID: e66967947cdb
Revises: 0001_extensions
Create Date: 2026-09-03 08:19:03.266178-03:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e66967947cdb"
down_revision: str | None = "0001_extensions"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ocurrido_en", sa.DateTime(timezone=True), nullable=False),
        sa.Column("procesado", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outbox_procesado"), "outbox", ["procesado"], unique=False)
    op.create_index(op.f("ix_outbox_tipo"), "outbox", ["tipo"], unique=False)
    op.create_table(
        "persona",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dni_hash", sa.String(length=64), nullable=False),
        sa.Column("dni_cifrado", sa.Text(), nullable=False),
        sa.Column("cuil_hash", sa.String(length=64), nullable=False),
        sa.Column("cuil_cifrado", sa.Text(), nullable=False),
        sa.Column("apellido", sa.String(length=120), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("celular", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("celular_verificado", sa.Boolean(), nullable=False),
        sa.Column("email_verificado", sa.Boolean(), nullable=False),
        sa.Column("estado_identidad", sa.String(length=20), nullable=False),
        sa.Column("metodo_verificacion", sa.String(length=20), nullable=True),
        sa.Column("fecha_alta", sa.DateTime(timezone=True), nullable=False),
        sa.Column("perfiles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_persona_cuil_hash"), "persona", ["cuil_hash"], unique=True)
    op.create_index(op.f("ix_persona_dni_hash"), "persona", ["dni_hash"], unique=True)
    op.create_table(
        "texto_legal",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.String(length=40), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("vigente", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tipo", "version", name="uq_texto_legal_tipo_version"),
    )
    op.create_index(op.f("ix_texto_legal_tipo"), "texto_legal", ["tipo"], unique=False)
    op.create_table(
        "consentimiento",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("tipo", sa.String(length=40), nullable=False),
        sa.Column("version_texto", sa.String(length=20), nullable=False),
        sa.Column("otorgado", sa.Boolean(), nullable=False),
        sa.Column("fecha", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=400), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_persona"],
            ["persona.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consentimiento_id_persona"), "consentimiento", ["id_persona"], unique=False
    )
    op.create_table(
        "credencial",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("hash", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_persona"],
            ["persona.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_credencial_id_persona"), "credencial", ["id_persona"], unique=True)
    op.create_table(
        "dispositivo",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("nombre_declarado", sa.String(length=120), nullable=False),
        sa.Column("plataforma", sa.String(length=40), nullable=False),
        sa.Column("huella", sa.String(length=128), nullable=False),
        sa.Column("fecha_alta", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fecha_ultimo_uso", sa.DateTime(timezone=True), nullable=False),
        sa.Column("estado", sa.String(length=20), nullable=False),
        sa.Column("autorizado_para_perfil_municipal", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_persona"],
            ["persona.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_dispositivo_id_persona"), "dispositivo", ["id_persona"], unique=False)
    op.create_table(
        "mfa",
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("secreto_cifrado", sa.Text(), nullable=False),
        sa.Column("activo", sa.Boolean(), nullable=False),
        sa.Column("codigos_recuperacion", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_persona"],
            ["persona.id"],
        ),
        sa.PrimaryKeyConstraint("id_persona"),
    )
    op.create_table(
        "refresh_token",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("id_persona", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("perfil", sa.String(length=60), nullable=False),
        sa.Column("creado", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expira", sa.DateTime(timezone=True), nullable=False),
        sa.Column("usado", sa.Boolean(), nullable=False),
        sa.Column("revocado", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_persona"],
            ["persona.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_family_id"), "refresh_token", ["family_id"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_token_id_persona"), "refresh_token", ["id_persona"], unique=False
    )
    op.create_index(
        op.f("ix_refresh_token_token_hash"), "refresh_token", ["token_hash"], unique=True
    )
    # NOTA: se eliminó el `op.drop_table('spatial_ref_sys')` que autogenerate agregó por
    # error: es una tabla interna de PostGIS y no debe tocarse.

    # Seed de textos legales vigentes (v1) para los cuatro consentimientos (§3.1).
    _seed_textos_legales()
    # ### end Alembic commands ###


def _seed_textos_legales() -> None:
    import uuid as _uuid

    tipos = [
        "TRATAMIENTO_DATOS",
        "COMUNICACIONES_COMERCIALES",
        "GEOLOCALIZACION",
        "ESTADISTICA_ANONIMA",
    ]
    filas = ", ".join(
        f"('{_uuid.uuid4()}', '{t}', 'v1', 'Texto legal {t} (v1).', true)" for t in tipos
    )
    op.execute("INSERT INTO texto_legal (id, tipo, version, texto, vigente) VALUES " + filas)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_token_token_hash"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_id_persona"), table_name="refresh_token")
    op.drop_index(op.f("ix_refresh_token_family_id"), table_name="refresh_token")
    op.drop_table("refresh_token")
    op.drop_table("mfa")
    op.drop_index(op.f("ix_dispositivo_id_persona"), table_name="dispositivo")
    op.drop_table("dispositivo")
    op.drop_index(op.f("ix_credencial_id_persona"), table_name="credencial")
    op.drop_table("credencial")
    op.drop_index(op.f("ix_consentimiento_id_persona"), table_name="consentimiento")
    op.drop_table("consentimiento")
    op.drop_index(op.f("ix_texto_legal_tipo"), table_name="texto_legal")
    op.drop_table("texto_legal")
    op.drop_index(op.f("ix_persona_dni_hash"), table_name="persona")
    op.drop_index(op.f("ix_persona_cuil_hash"), table_name="persona")
    op.drop_table("persona")
    op.drop_index(op.f("ix_outbox_tipo"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_procesado"), table_name="outbox")
    op.drop_table("outbox")
    # ### end Alembic commands ###
