"""Puertos del módulo grupo."""

from __future__ import annotations

from typing import Protocol

from tarjeta.shared.domain.events import DomainEvent
from tarjeta.shared.domain.types import EntityId

from .grupo import Grupo
from .invitacion import Invitacion
from .miembro import Miembro


class GrupoRepository(Protocol):
    async def agregar(self, grupo: Grupo) -> None: ...
    async def guardar(self, grupo: Grupo) -> None: ...
    async def obtener(self, id: EntityId) -> Grupo | None: ...
    async def por_titular(self, id_persona: str) -> Grupo | None: ...

    # Miembros (el titular también es una fila, con rol TITULAR).
    async def agregar_miembro(self, miembro: Miembro) -> None: ...
    async def guardar_miembro(self, miembro: Miembro) -> None: ...
    async def miembro_de(self, id_persona: str) -> Miembro | None:
        """Membresía activa de la persona en cualquier grupo (una persona, un grupo). §10.2."""
        ...

    async def miembro_en(self, id_grupo: EntityId, id_persona: str) -> Miembro | None: ...
    async def miembros_activos(self, id_grupo: EntityId) -> list[Miembro]: ...


class InvitacionRepository(Protocol):
    async def agregar(self, invitacion: Invitacion) -> None: ...
    async def guardar(self, invitacion: Invitacion) -> None: ...
    async def por_token(self, token: str) -> Invitacion | None: ...


class AlertaRepository(Protocol):
    async def registrar(self, *, id_grupo: str, tipo: str, detalle: str) -> None: ...
    async def de_grupo(self, id_grupo: str) -> list[tuple[str, str, str]]: ...


class AvisoRepository(Protocol):
    """Avisos visibles para una persona (§11.0.C: el sucesor se entera al entrar)."""

    async def registrar(self, *, id_persona: str, tipo: str, texto: str) -> None: ...
    async def pendientes(self, id_persona: str) -> list[tuple[str, str]]: ...
    async def marcar_vistos(self, id_persona: str) -> None: ...


class Outbox(Protocol):
    async def escribir(self, eventos: list[DomainEvent]) -> None: ...
