"""Puertos del módulo gobierno."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from tarjeta.shared.domain.types import EntityId

from .aprobacion import SolicitudAprobacion
from .auditoria import RegistroAuditoria
from .roles import RolMunicipal


class AuditoriaRepository(Protocol):
    async def agregar(self, registro: RegistroAuditoria) -> None: ...
    async def existe_evento(self, id_evento_origen: str) -> bool: ...
    async def listar(
        self,
        *,
        actor: str | None,
        accion: str | None,
        entidad: str | None,
        limite: int,
        offset: int,
    ) -> list[RegistroAuditoria]: ...


class AprobacionRepository(Protocol):
    async def agregar(self, solicitud: SolicitudAprobacion) -> None: ...
    async def obtener(self, id: EntityId) -> SolicitudAprobacion | None: ...
    async def guardar(self, solicitud: SolicitudAprobacion) -> None: ...
    async def listar_pendientes(self) -> list[SolicitudAprobacion]: ...
    async def expirar_vencidas(self, ahora: datetime) -> int: ...


class ParametroRepository(Protocol):
    async def obtener(self, clave: str) -> int | None: ...
    async def todos(self) -> dict[str, int]: ...
    async def guardar(self, clave: str, valor: int) -> None: ...


class AgenteRepository(Protocol):
    async def rol_de(self, id_persona: EntityId) -> RolMunicipal | None: ...
    async def asignar(self, id_persona: EntityId, rol: RolMunicipal) -> None: ...
    async def listar(self) -> list[tuple[str, RolMunicipal]]: ...


class RecaudacionRepository(Protocol):
    async def transiciones_a_black_post_registro(self) -> int: ...
    async def distribucion_por_nivel(self) -> dict[str, int]: ...
