"""Puertos del módulo puntos."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from tarjeta.shared.domain.events import DomainEvent
from tarjeta.shared.domain.types import EntityId

from .billetera import Billetera
from .catalogo import ComprobanteInventario, ItemCatalogo
from .lote import LotePuntos
from .moneda import TipoMoneda, TipoTitular
from .movimiento import MovimientoBilletera


class BilleteraRepository(Protocol):
    async def obtener_o_crear(
        self,
        *,
        tipo_titular: TipoTitular,
        id_titular: str,
        tipo_moneda: TipoMoneda,
        id_comercio: str | None,
    ) -> Billetera:
        """Devuelve la billetera bloqueada (FOR UPDATE); la crea si no existe. Serializa todas
        las mutaciones del saldo de esa billetera (§09.2)."""
        ...

    async def obtener(
        self,
        *,
        tipo_titular: TipoTitular,
        id_titular: str,
        tipo_moneda: TipoMoneda,
        id_comercio: str | None,
    ) -> Billetera | None: ...

    async def ajustar_saldo(self, id_billetera: EntityId, delta: int) -> int:
        """Ajuste atómico del saldo en la base (no leído-y-sumado). Devuelve el nuevo saldo."""
        ...

    async def bloquear(self, id_billetera: EntityId) -> Billetera | None:
        """Bloquea la billetera por id (FOR UPDATE) para serializar mutaciones (vencimiento)."""
        ...

    async def pc_de_titular(self, id_titular: str) -> list[Billetera]: ...
    async def por_id(self, id_billetera: EntityId) -> Billetera | None: ...


class LoteRepository(Protocol):
    async def agregar(self, lote: LotePuntos) -> None: ...
    async def obtener(self, id_lote: EntityId) -> LotePuntos | None: ...
    async def disponibles_fifo(self, id_billetera: EntityId, hoy: date) -> list[LotePuntos]: ...
    async def descontar(self, id_lote: EntityId, cantidad: int) -> None: ...
    async def por_vencer(
        self, id_billetera: EntityId, desde: date, hasta: date
    ) -> list[LotePuntos]: ...
    async def vencidos_pendientes(self, hoy: date, limite: int) -> list[LotePuntos]: ...
    async def marcar_vencido(self, id_lote: EntityId) -> None: ...


class MovimientoRepository(Protocol):
    async def agregar(self, movimiento: MovimientoBilletera) -> None: ...
    async def existe(self, clave_dedup: str) -> bool: ...
    async def suma(self, id_billetera: EntityId) -> int: ...
    async def listar(self, id_billetera: EntityId, limite: int) -> list[MovimientoBilletera]: ...
    async def por_transaccion(self, id_transaccion: str) -> list[MovimientoBilletera]: ...
    # §09.7: pasivo del comercio (PC emitidos y canjeados) y pasivo del municipio (PM en
    # circulación = suma de saldos de las billeteras de PM).
    async def resumen_comercio(self, id_comercio: str) -> tuple[int, int]: ...
    async def pm_en_circulacion(self) -> int: ...


class ItemCatalogoRepository(Protocol):
    async def agregar(self, item: ItemCatalogo) -> None: ...
    async def obtener(self, id: EntityId) -> ItemCatalogo | None: ...
    async def listar_activos(self, hoy: date) -> list[ItemCatalogo]: ...
    async def listar_todos(self) -> list[ItemCatalogo]: ...
    async def reservar_stock(self, id: EntityId) -> bool:
        """Reserva un cupo de forma atómica (UPDATE ... WHERE stock > 0 RETURNING). §09.5."""
        ...


class ComprobanteInventarioRepository(Protocol):
    async def agregar(self, comprobante: ComprobanteInventario) -> None: ...
    async def de_persona(self, id_persona: str) -> list[ComprobanteInventario]: ...


class Outbox(Protocol):
    async def escribir(self, eventos: list[DomainEvent]) -> None: ...
